# XML output to test/ref/testWithXmlVerbose51.xml
# Started on 01/06/15 23:38:21
# Starting class: TestFailuresWithXml
# Starting test: TestFailuresWithXml.test_failure_with_cdata_xml
# Failure: test/test_with_xml.lua:13: expected: "got it"
actual: "cdata does not like ]]>"
# stack traceback:
	.\luaunit.lua:476: in function 'assertEquals'
	test/test_with_xml.lua:13: in function 'TestFailuresWithXml.test_failure_with_cdata_xml'
	.\luaunit.lua:1426: in function <.\luaunit.lua:1426>
	[C]: in function 'xpcall'
	.\luaunit.lua:1426: in function 'protectedCall'
	.\luaunit.lua:1483: in function 'execOneFunction'
	.\luaunit.lua:1582: in function 'runSuiteByInstances'
	.\luaunit.lua:1635: in function 'runSuiteByNames'
	.\luaunit.lua:1711: in function <.\luaunit.lua:1651>
	(tail call): ?
	test/test_with_xml.lua:17: in main chunk
	[C]: ?
# Starting test: TestFailuresWithXml.test_failure_with_simple_xml
# Failure: test/test_with_xml.lua:9: expected: "got it"
actual: '<toto>ti"ti</toto>'
# stack traceback:
	.\luaunit.lua:476: in function 'assertEquals'
	test/test_with_xml.lua:9: in function 'TestFailuresWithXml.test_failure_with_simple_xml'
	.\luaunit.lua:1426: in function <.\luaunit.lua:1426>
	[C]: in function 'xpcall'
	.\luaunit.lua:1426: in function 'protectedCall'
	.\luaunit.lua:1483: in function 'execOneFunction'
	.\luaunit.lua:1582: in function 'runSuiteByInstances'
	.\luaunit.lua:1635: in function 'runSuiteByNames'
	.\luaunit.lua:1711: in function <.\luaunit.lua:1651>
	(tail call): ?
	test/test_with_xml.lua:17: in main chunk
	[C]: ?
# Ran 2 tests in 0.000 seconds, 0 successes, 2 failures
