# XML output to test/ref/testWithXmlVerbose.xml
# Started on 01/09/15 00:13:12
# Starting class: TestFailuresWithXml
# Starting test: TestFailuresWithXml.test_failure_with_cdata_xml
# Failure: test/test_with_xml.lua:13: expected: "got it"
actual: "cdata does not like ]]>"
# stack traceback:
	.\luaunit.lua:476: in function 'assertEquals'
	test/test_with_xml.lua:13: in function 'TestFailuresWithXml.test_failure_with_cdata_xml'
	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
	[C]: in function 'xpcall'
	.\luaunit.lua:1432: in function 'protectedCall'
	.\luaunit.lua:1489: in function 'execOneFunction'
	.\luaunit.lua:1588: in function 'runSuiteByInstances'
	.\luaunit.lua:1641: in function 'runSuiteByNames'
	.\luaunit.lua:1717: in function <.\luaunit.lua:1657>
	(...tail calls...)
	test/test_with_xml.lua:17: in main chunk
	[C]: in ?
# Starting test: TestFailuresWithXml.test_failure_with_simple_xml
# Failure: test/test_with_xml.lua:9: expected: "got it"
actual: '<toto>ti"ti</toto>'
# stack traceback:
	.\luaunit.lua:476: in function 'assertEquals'
	test/test_with_xml.lua:9: in function 'TestFailuresWithXml.test_failure_with_simple_xml'
	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
	[C]: in function 'xpcall'
	.\luaunit.lua:1432: in function 'protectedCall'
	.\luaunit.lua:1489: in function 'execOneFunction'
	.\luaunit.lua:1588: in function 'runSuiteByInstances'
	.\luaunit.lua:1641: in function 'runSuiteByNames'
	.\luaunit.lua:1717: in function <.\luaunit.lua:1657>
	(...tail calls...)
	test/test_with_xml.lua:17: in main chunk
	[C]: in ?
# Ran 2 tests in 0.000 seconds, 0 successes, 2 failures
